### ISSUE TITLE
Dropdown to change between different bridges.

### ISSUE THREAD

**Issue by mfornet** [near/rainbow-bridge-frontend#104]
There will be several bridges running at the same time between different networks (Near mainnet, Near testnet, Ethereum Mainnet, Rinkeby and Ropsten). 

The relevant difference between them from the frontend point of view, are the addresses of deployment and endpoint RPC. We should have a dropdown on the UI that allows user to change between bridges, (similar to how it is done in the [explorer](https://explorer.near.org/))

**Comment by paouvrard** [comment]
The frontend could also connect to the correct bridge based on the network used in the Ethereum wallet (metamask/walletconnect)

- Ropsten/Rinkeby selected on metamask -> Use Near testnet and wallet.testnet.near.org
- Ethereum Mainnet selected on metamask -> Use Near Mainnet and wallet.near.org

Or if the frontend is hosted on different urls, https://bridge.rinkeby-testnet.near.org / https://bridge.ropsten-testnet.near.org, the user can be prompted to change network if the Wallet is connected to the wrong one.
This is the process used by the GnosisSafe: https://rinkeby.gnosis-safe.io/app, I found it quite intuitive.

**Comment by paouvrard** [comment]
Implemented in #120
