### ISSUE TITLE
Host frontend in custom domain

### ISSUE THREAD

**Issue by mfornet** [near/rainbow-bridge-frontend#105]
The bridge frontend should be served at `*.near.org` url rather than in `*.github.io` for production.

We can keep `*.github.io` for staging, testing and iterating fast on new changes, but ultimately the stable and trusted deployment of the bridge should be at `bridge.near.org`.

After #104 we can have different url for different bridges, such that is clear for the user reading at the URL which bridge they are using. (Example https://bridge.rinkeby-testnet.near.org / https://bridge.ropsten-testnet.near.org)

**Comment by djsatok** [comment]
The frontend to be hosted on
ethereum.bridgetonear.org -- Ethereum <> NEAR
ropsten.bridgetonear.org -- Ropsten <> NEAR Testnet
rinkeby.bridgetonear -- Rinkeby <> NEAR Testnet

**Comment by djsatok** [comment]
Completed
