### ISSUE TITLE
Remove withdraw/lock access keys

### ISSUE THREAD

**Issue by paouvrard** [near/rainbow-bridge-frontend#106]
The withdraw() function of the BridgeToken should be #[payable] like the ft_transfer() of NEP141 and require a near deposit so that it is not possible to transact with an access key to that token contract. Instead the user should always sign a withdraw/lock transaction via the near wallet.

Minting/unlocking on near can be done safely with access keys as the receiver and amount are determined at lock/burn.

Once the change has been made and NEP141 is applied, this rainbow-bridge-frontend interface will have to be updated since it currently uses access keys for withdraw/lock on the near side.

**Comment by mfornet** [comment]
`withdraw` function is now payable. The frontend can be updated with the new change. (However it is not deployed yet)

**Comment by paouvrard** [comment]
Note: we don't want to deploy the new `withdraw` with payable and attached deposit until the frontend is implemented otherwise it will break the current flow with frontend access keys. Pending https://github.com/near/rainbow-bridge-frontend/issues/98 with near wallet redirect transaction hashes.

**Comment by mfornet** [comment]
@paouvrard this update is not necessary since we are moving away from NEP21 to NEP141. There are similar requirements for the new interface, but several things will change including workflow, so will close this.

**Comment by paouvrard** [comment]
Fixed in https://github.com/near/rainbow-bridge-client/pull/7
