### ISSUE TITLE
Bug: Recovery from Failed Block Syncing (and other polling related bugs)

### ISSUE THREAD

**Issue by mattlockyer** [near/rainbow-bridge-frontend#123]
I was syncing blocks on the frontend and it got to 25/30.

Said "Failed" and the UI went red.

I clicked retry.

It is now orange, but still stuck at 25/30 block.

Now my TST isn't minted on the receiving side.

It's been several minutes now. Nothing on explorer.

Not sure what appropriate course of action is?

Perhaps we need some sort of unlocking if tokens are stuck and not minted?

![image](https://user-images.githubusercontent.com/321340/109428826-a0434b80-79ad-11eb-80f3-4fdb727d1f90.png)

![image](https://user-images.githubusercontent.com/321340/109428839-a9ccb380-79ad-11eb-8bda-43d139a018e9.png)

**Comment by mattlockyer** [comment]
Ok I needed to fully refresh my browser window (several minutes later) and it's now showing blue ready to mint.

Something with the client library not updating? / checking? / if it gets stuck? I will look into this and see if I can update the polling / state refreshing on the UI.

**Comment by mattlockyer** [comment]
Ok mint now telling me it failed with no recourse.

Tried 2 reties, here's the explorer output:

![image](https://user-images.githubusercontent.com/321340/109430128-7ccfcf00-79b4-11eb-95e8-ea88a44ea7aa.png)

![image](https://user-images.githubusercontent.com/321340/109430115-6aee2c00-79b4-11eb-8446-19c6e713a5a6.png)

**Comment by mattlockyer** [comment]
Also seems like can't lock multiple deposits at once on the ethereum side?
![image](https://user-images.githubusercontent.com/321340/109430167-c28c9780-79b4-11eb-8da7-beeef13add8b.png)

**Comment by mattlockyer** [comment]
Ok when mint fails on UI, it actually succeeded so it should poll and recheck.

Looking into this.

I think 90% of the issues I just presented are a result of

1. not saving the user's action (what did they want to do)
2. preventing them from doing something else (moving around UI and locking more tokens)
3. aggressively polling re: previous actions

Also balances should be shown at all times on the UI somewhere for both accounts.

![image](https://user-images.githubusercontent.com/321340/109430311-8b6ab600-79b5-11eb-8d83-11ea9821c79f.png)

**Comment by mattlockyer** [comment]
I'll make a PR today. I also need to familiarize myself with the client libraries!

**Comment by paouvrard** [comment]
Thank you Matt for the detailed review !
Those issues should now be solved in this PR: https://github.com/near/rainbow-bridge-client/pull/7/files
Ability to remove transfers should be added soon: https://github.com/near/rainbow-bridge-frontend/issues/136
