### ISSUE TITLE
Possible bug: is rainbow-bridge-frontend broken?

### ISSUE THREAD

**Issue by zavodil** [near/rainbow-bridge-frontend#131]
I cant see my transfers but I see console errors like this:

Error: Unregistered library for transfer with type=@near~eth/nep141~erc20/natural-erc20/sendToNear
Error: Can't find library for transfer with type=@near~eth/nep141~erc20/natural-erc20/sendToNear

Source: https://near.github.io/rainbow-bridge-frontend
![Clip2net_210303165837](https://user-images.githubusercontent.com/38926321/109824685-b8cb9400-7c41-11eb-9853-c60ed7af2708.png)

**Comment by paouvrard** [comment]
Please delete your localStorage as old transfers and no longer compatible after the recent refactoring.
Application -> Local Storage -> delete rainbow-bridge-transfers
