### ISSUE TITLE
Improve balance display on eth accountsChanged

### ISSUE THREAD

**Issue by paouvrard** [near/rainbow-bridge-frontend#134]
On a new transfer page, if the user changes Ethereum account, the balances should be queried again.

- Ethereum -> Near: update "Available to transfer"
![image](https://user-images.githubusercontent.com/29397451/109974265-b863f380-7d3c-11eb-90bf-1ca539954440.png)

- Near -> Ethereum: update "Current balance" in To (destination)
![image](https://user-images.githubusercontent.com/29397451/109973441-bcdbdc80-7d3b-11eb-96ce-b1723bfba8c8.png)

**Comment by paouvrard** [comment]
This will require changes to the way the new transfer page is rendered:
https://github.com/near/rainbow-bridge-frontend/blob/6f794472ff6f21398fe2fe47a4aedd2318579e6e/src/html/erc20-form.html#L189

**Comment by mfornet** [comment]
@paouvrard was this solved?

**Comment by paouvrard** [comment]
yes, page will reload on accounts changed (not yet merged)
