### ISSUE TITLE
Add notification (top) that Ledger-protected accounts are not supported at the moment

### ISSUE THREAD

**Issue by djsatok** [near/rainbow-bridge-frontend#149]
Ledger-based wallets are not able to sign finalisation transactions. See more here: https://github.com/near/rainbow-token-connector/issues/48

**Comment by paouvrard** [comment]
![image](https://user-images.githubusercontent.com/29397451/111725417-5f529e80-88aa-11eb-9402-c02e7d309091.png)
Does this affect only `deposit` and not `withdraw`. We could also mention that the finalization tx signer doesn't have to be the recipient.

**Comment by djsatok** [comment]
This affects only deposit. How we can allow people to finalise transactions with other accounts?

**Comment by paouvrard** [comment]
Users can login with any account to finalize a transaction created and recorded on the same browser.
If finalizing from another browser, they can first use the restore feature and then finalize with any account as before.

**Comment by djsatok** [comment]
Completed
