### ISSUE TITLE
"Approve" TX must be sent even if the vault is already approved

### ISSUE THREAD

**Issue by kcole16** [near/rainbow-bridge-frontend#155]
### Overview
I started an "Approve" TX, then used the MetaMask "speed up" feature to get the TX mined quicker. By doing this, the frontend never detected my successful TX (likely due to the TX having a different hash than the original), and there was no way for me to advance in the flow. I had to send another "Approve" TX, even though I'd just approved the contract.

### Expected Behavior
If I've approved the vault for a token at any time, I shouldn't have to re-approve.

### Steps to Reproduce
1. Click "Approve Transfer"
2. Authorize the TX in MetaMask
3. Either click "Speed Up" in MetaMask, or leave the page and clear the browser cache
4. The only path forward is to click "Approve" again and sign another, redundant TX

**Comment by djsatok** [comment]
Thanks for submitting the issue!
This is a combination of #139 and #136
