### ISSUE TITLE
Sorting of the token list

### ISSUE THREAD

**Issue by dafacto** [near/rainbow-bridge-frontend#165]
Currently the token list appears to be unsorted—USDT, UNI, LINK, USDC, WBTC, AAVE, CRO...

As a user, here's how I'd want to see the sort:

1. Popular tokens
2. Tokens for which I have a balance.
3. All the rest

For example:

- ETH
- USDT
- USDC (29,210.18)
- DAI
- WBTC
- -------
- ALCX (18.345)
- RULER (12.456)
- -------
- AAVE
- BUSD
- CRO
- GRT
- ...

**Comment by paouvrard** [comment]
Released v3.4.3
