### ISSUE TITLE
Pasting the contract address of the currently chosen token doesn't close selector

### ISSUE THREAD

**Issue by dafacto** [near/rainbow-bridge-frontend#166]
In the token chooser, if the user pastes the contract address for a non-listed token, and hits return, the selector closes, and the input displays the symbol for the token living at the pasted contract address.

If the user then repeats the same process, pasting in the contract address again, and hits return, the selector does NOT close.

Here's a screen recording:

http://d.dafacto.com/XOlzHx

**Comment by paouvrard** [comment]
Released v3.4.3
