### ISSUE TITLE
Confirmation on transfer deletion?

### ISSUE THREAD

**Issue by dafacto** [near/rainbow-bridge-frontend#169]
I wanted to test if clicking the delete icon prompts for confirmation before removal, but since I was in the middle of a transfer, I thought I'd just post the question here:

![](http://d.dafacto.com/5DyvB5+)

**Comment by paouvrard** [comment]
![image](https://user-images.githubusercontent.com/29397451/113100578-8ad47200-9236-11eb-8b03-7b5d09e97541.png)
yes ! May need some wording improvement ~

**Comment by paouvrard** [comment]
Fixed here: https://github.com/near/rainbow-bridge-frontend/pull/175
![image](https://user-images.githubusercontent.com/29397451/113146297-7316e100-926a-11eb-96a5-631920b76521.png)
