### ISSUE TITLE
Cannot see full address of recently-deployed contract

### ISSUE THREAD

**Issue by mikedotexe** [near/rainbow-bridge-frontend#207]
In the clip here, I'm selecting a contract address but cannot see the full value. It feels like there is enough real estate in the UI to show this info and we may have to have that discoverable or copy/pastable.

![cannot-see-address](https://user-images.githubusercontent.com/1042667/114574098-cce5b680-9c2d-11eb-9718-3b1b977181e4.gif)

**Comment by mfornet** [comment]
Discussed offline, this wasn't the correct address, it is working for the right address.
