### ISSUE TITLE
send novel NEP21 to Eth

### ISSUE THREAD

**Issue by chadoh** [near/rainbow-bridge-frontend#25]
- [ ] UI for searching for a whitelist of NEP21 tokens, set by environment variables
- [ ] allow setting unlisted NEP21 via URL param (show warning for these)
- if user selects NEP21 that has no matching NEP21-as-ERC20 deployed via Token Factory in Ethereum
  - [ ] UI explains situation
  - [ ] user can pay tx / storage fee to deploy ERC20 Wrapper

**Comment by djsatok** [comment]
Closing for now, to be implemented not sooner than end of Q2 / Q3 2021
