### ISSUE TITLE
send specific NEP21 to Eth via Generic Connector

### ISSUE THREAD

**Issue by chadoh** [near/rainbow-bridge-frontend#26]
The frontend at https://near.github.io/rainbow-bridge-frontend/ should allow sending a specific NEP21, with a hard-coded address for now, across to Ethereum. This will require using the CLI to deploy an ERC20 to wrap it on the Ethereum side using the Factory contract.

This may take some collaboration with a designer to figure out a sensible way to show all of these new options.

**Comment by djsatok** [comment]
Closing for now, to be implemented not sooner than end of Q2 / Q3 2021
