### ISSUE TITLE
The finalization transaction step is not performed correctly

### ISSUE THREAD

**Issue by djsatok** [near/rainbow-bridge-frontend#80]
<img width="423" alt="Screenshot 2021-02-03 at 14 59 08" src="https://user-images.githubusercontent.com/5417224/106750439-8756ad00-6630-11eb-8e2c-b18eb8dc3f07.png">

**Comment by chadoh** [comment]
Fixed. I've gotten some transfers to successfully complete. Sometimes there are still confusing errors, but no longer this one.

**Comment by chadoh** [comment]
Oh, fixed in b679d98666ad0fbaed9a1f00de9b95ccfb6027c8
