### ISSUE TITLE
Bug in querying of token balances that prevents doing transfers

### ISSUE THREAD

**Issue by djsatok** [near/rainbow-bridge-frontend#82]
Bridge FE does not query correctly the balances of the tokens and because of this does not allow to start the transfer.

<img width="512" alt="Screenshot 2021-02-05 at 15 50 38" src="https://user-images.githubusercontent.com/5417224/107042119-09c6a480-67ca-11eb-888e-ea9016344ae8.png">
<img width="910" alt="Screenshot 2021-02-05 at 15 50 50" src="https://user-images.githubusercontent.com/5417224/107042124-0b906800-67ca-11eb-8a73-c87f3b2ecef7.png">

**Comment by mfornet** [comment]
Is this still an issue, or we should close it after: https://github.com/near/rainbow-bridge/issues/475
