### ISSUE TITLE
Bug report: invalid digit found in string

### ISSUE THREAD

**Issue by zavodil** [near/rainbow-bridge-frontend#91]
Rust throw an exception about  "invalid digit found in string" when we transfer amount of tokens with the numeric separator (0.5, 0.777 etc)

![photo_2021-02-11_23-58-36](https://user-images.githubusercontent.com/38926321/107762980-84e20a80-6d36-11eb-8205-be290e626b38.jpg)

**Comment by djsatok** [comment]
This is closely related to #78 and #79

**Comment by djsatok** [comment]
Fixed in #99
