### ISSUE TITLE
checkMint() may give the wrong result

### ISSUE THREAD

**Issue by paouvrard** [near/rainbow-bridge-frontend#98]
checkMint() gives a failed transfer status if `balanceBefore + transfer.amount != balanceAfter`.
But the user may be doing other transfers (via bridge or regular token transfer) so checkMint() may give a failed status even though the mint transaction was successful.

The same problem can occur when the near.wallet informs : `Error: send_tx_commit has timed out` (balanceAfter queried before the tx is executed ?)

**Comment by mfornet** [comment]
Good point. Also it can return successful transfer status even though tx may have failed due the same reasons. 

We should instead check the status of the transaction to determine if it was successful, rather than on the balance.

**Comment by djsatok** [comment]
Perhaps this is the issue that I've experienced today. See the screen.
<img width="412" alt="Screenshot 2021-02-24 at 00 13 53" src="https://user-images.githubusercontent.com/5417224/108915234-3cc7bf80-7635-11eb-88de-32f62abc47f2.png">

The error message displayed a 0.1 sec before I got redirected to the wallet. Then in wallet I've signed the transaction and it successfully completed: https://explorer.testnet.near.org/transactions/EnciJ36nqQSupUgXSWrXYNSN42vBHgNkeMJ3DfbX2Ui8

**Comment by paouvrard** [comment]
also don't checkStatus() when user selected the wrong Ethereum network otherwise errors will be recorded in localStorage transfers history which we don't want. #120

**Comment by djsatok** [comment]
Most probably same issue is indicated in #123

**Comment by chadoh** [comment]
The underlying cause is the URL Params workaround being used in the absence of https://github.com/near/near-api-js/pull/467 + https://github.com/near/near-wallet/pull/1377

Once we have `nearConnection.completedTransactions` available, we can stop updating the URL before the `mint` call, since we will be able to more directly check the outcome of the `mint` transaction. Then the non-deterministic "minting marked as failure before user even gets redirected" bug goes away, and the library becomes more straightforward to adapt to a Node/CLI environment.

**Comment by chadoh** [comment]
Note that this `completedTransactions` feature would also enable refactoring `withdraw` logic in this app to be more robust, and allow making `withdraw` tx require a redirect to NEAR Wallet

**Comment by paouvrard** [comment]
@djsatok @vgrichina  In order to fix these chechStatus() issues, I think the minimal requirement is for the near wallet redirect to inform the broadcasted transaction hash to the dapp (bridge frontend) as a url param: near/near-wallet#1377. Because currently this dapp frontend doesn't have a way of knowing the status of near transactions.

The near/near-api-js#467 is a more general solution for near-api-js to handle these redirects but not necessary to fix the current bridge issues. I'd be happy to look into the near-api-js feature later after we have a working solution for this frontend.

**Comment by vgrichina** [comment]
> The same problem can occur when the near.wallet informs : Error: send_tx_commit has timed out (balanceAfter queried before the tx is executed ?)


is this still happening for anyone? this is supposed to be fixed in wallet already

**Comment by vgrichina** [comment]
> @djsatok @vgrichina In order to fix these chechStatus() issues, I think the minimal requirement is for the near wallet redirect to inform the broadcasted transaction hash to the dapp (bridge frontend) as a url param: [near/near-wallet#1377](https://github.com/near/near-wallet/pull/1377). Because currently this dapp frontend doesn't have a way of knowing the status of near transactions.
> 
> The [near/near-api-js#467](https://github.com/near/near-api-js/pull/467) is a more general solution for near-api-js to handle these redirects but not necessary to fix the current bridge issues. I'd be happy to look into the near-api-js feature later after we have a working solution for this frontend.

https://github.com/near/near-wallet/pull/1377

there is PR which allows to pass any metadata to wallet and get it back when redirected
you also get transaction hashes back

I think it should be sufficient to get you going, I might have to add some changes to support 2FA accounts as well (before releasing this in wallet).

**Comment by paouvrard** [comment]
> > The same problem can occur when the near.wallet informs : Error: send_tx_commit has timed out (balanceAfter queried before the tx is executed ?)
> 
> is this still happening for anyone? this is supposed to be fixed in wallet already

Not happening anymore.

> near/near-wallet#1377
> there is PR which allows to pass any metadata to wallet and get it back when redirected
you also get transaction hashes back

This PR was tested here: https://github.com/near/rainbow-bridge-client/pull/7 working well

> I think it should be sufficient to get you going, I might have to add some changes to support 2FA accounts as well (before releasing this in wallet).

Succeeded in signing transactions with email 2FA enabled (is it expected behavior that the 2FA code is not prompted even if there is a deposit?)

**Comment by paouvrard** [comment]
Fixed in https://github.com/near/rainbow-bridge-client/pull/7
